FROM ubuntu

ENV JULIA_VERSION=1.0

RUN curl -fL "https://julialang.s3.amazonaws.com/bin/linux/x64/${JULIA_VERSION%[.-]*}/julia-${JULIA_VERSION}-linux-x86_64.tar.gz" | tar -xf > /tmp/julia-linux

RUN wget "https://github.com/JuliaLang/julia/releases/download/v1.5.3/julia-1.5.3-full.tar.gz" \
	&& tar -xvf julia-1.5.3-full.tar.gz \
	&& rm -rf julia-1.5.3-full.tar.gz

CMD ["/bin/bash"]
