FROM ubuntu

ENV JULIA_VERSION=1.0

# No verification
RUN curl -fL "https://julialang.s3.amazonaws.com/bin/linux/x64/${JULIA_VERSION%[.-]*}/julia-${JULIA_VERSION}-linux-x86_64.tar.gz" | tar -xf > /tmp/julia-linux

# No verification
RUN wget "https://github.com/JuliaLang/julia/releases/download/v1.5.3/julia-1.5.3-full.tar.gz" \
	&& tar -xvf julia-1.5.3-full.tar.gz \
	&& rm -rf julia-1.5.3-full.tar.gz

# curl bashing examples. Allow only when the domain is in safe list
RUN curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

ENV URL=example.com
RUN curl -s http://${URL}/install.sh | sh

RUN sh <(curl https://example.sh)

FROM centos:8

# An rpm package is directly downloaded and installed
# Ensure the domain is in the allowed list of domains
# Ensure package was verified before installation. `rpm -K` or `debsig-verify`
RUN curl -LO ${CURL_OPTIONS} \
      http://vault.centos.org/7.0.1406/os/x86_64/Packages/wget-1.14-10.el7.x86_64.rpm && \
    yum -y install wget-1.14-10.el7.x86_64.rpm

# Package was manually installed by downloading from an internet location without performing verification
RUN curl -LO ${CURL_OPTIONS} \
      https://sourceforge.net/projects/p7zip/files/p7zip/9.20.1/p7zip_9.20.1_src_all.tar.bz2 && \
    bzcat p7zip_9.20.1_src_all.tar.bz2 | tar x && \
    cd p7zip_9.20.1 && \
    cp install.sh install.sh.orig

CMD ["/bin/bash"]
